### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Rohitsingh385**
README created and updated

### CODE REVIEW

**Comment by Rohitsingh385** [comment]
hi can you check the new readme file, and do you want me to add anything else? plss let me know :)

**Comment by just-injoey** [comment]
I am merging this pull request but it would be better if u also include all the libraries/modules to be installed like,

pip install pyttsx3
pip install tkinter

**Comment by Rohitsingh385** [comment]
Done.can you review the changes, this is all we have to install right?

**Comment by Rohitsingh385** [comment]
Hey just a reminder did u checked the updated file

**Pull request merged**
